travis:
  secure:
    BINSTAR_TOKEN: ofXnai22ej8zg6REg/PzMHXeadsH6PVy+/9ppRdahq0wEcUWhpAABHxiW+++fLw+QRaUm4NO8r6kTIPj1XA4P78YQJELld9CBAjSL9dtfSRUl2l/ZwS4y3l1ziA4BilWOkQCo57TvoTp81bMJ6QIhsdECaEp0TfwlHFkhK/v3yILiANncrT5NKyx3Os/kLd7paGt9bmS9hwm+DyKCu7Jr2YQ7onsuhXHRVtll5skonJhD9abO8Vi1nGjACnLXgzzinHRwQr1a4DI3xje12cdS/AljLaxdztUAUsGL/jWQPPz/4L1DY7McwMhE8rHmaXJkzBvZibN53qDmn/Z/N3D5qsvfKmZtFoUPGqWr0SV2Uj8skcZEInDy7Dqd0dChEByqj0aru9Ihh2tywHP0VWuQoF2rwrqK5DgoZeYg/yfdR4ERMM/QtKfUvYk2fq5UdiLpYVVogIXX4sSDBIjNE/L89fFrXt+AYClYnoRLa3F7PWsaE2GrIAtQ/hHFOjAIAfsHXwn6FcwiXJiCtdv+cy+t5uQ/HZr045qo2tKS1LDgQ8ULEx32+7npbn4oDDi9RM+/0kVczcY3586Rt5uC+nIBZAehW3PqLO8pAmDJRLy3pcXbWleLLBM639JhrikVropfmJLG/x2zq6TJqLsIhUGJiakqk3CXTx7isz0urlQbek=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
