travis:
  secure:
    BINSTAR_TOKEN: DZHUVqqqmp+xgk+4xhwncVDOi3QB1Ih5mAQgonaTmLtss6p9GwXW3ytWLBW5YoCNvHfZvz47cS1JO9h9xCZ/8wSjHtELdisGhs9kV0PlPUk2UK2JBU2gvhgQwFn8c795BvrSwU+09C6S3oPIbcPiLgI73eKThGStw4McMnrqfELiVVMuZfFPowBTZJymQf79/nbFBWipml5UY2MxQqqRihh99HQPfwddga/Dr/tr8bzTH/SditJo9rmEaXS0r7He8Bu/gpXIw53Llf9ddtSyq7K6HG9cDsKOGyGxwl//r8frRrODuhEwESc5r+dHxltBYJuRGhgDVwqZmiel72OfPuHDwGTT9iXu+gsunlbo5qfr0iFYRJRpZvQlIFIMzUxWg3JZhkBfaCrIIk5IOxkB1x0c1G8KjsY7tPg0OQBogN83xaZL91b9PcSWeT0Lk1y94h3MoOEOdGNDS+hKRHUuZzJFDvAb4ehADIwia3PwQWwVYsW29qfqIbBK/lmXXCiCimPIBLHLRcMPt5V5yyxx8cicwI/fHyOg7BwAlQPttfg4fbHSgDiYH9x87JYOKjINgjluh1iMwnVuRWAaVb5w8R5wRCOPl16RR2C6AaNHEe7Zib5iMozKYqU5Sk6CVDiA3PSRS228O6pUU4ZZzBI6sFUhh4Pjfq655+BbLSs18xE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
