travis:
  secure:
    BINSTAR_TOKEN: P9ng9OYJ9B/sRASdkL06nNEL9ddXgOLTUi9f1Fy0Kg/mKEd4KS0TOaXFtp7aB6QuuLAFDgP+r40xyJeeNCUwlC3LX2NojeP4laKF1Ck4+FaTOCWomQzuHQtYd87pvSg2Mx7CzPIXIeaKFbBc8z5fBWb5rF1I2D2nuOHBeU1gfKuOOqGMxuOzPTOBy5De3SJ0cIkGzis8GWr4h/bUMv6Tj4EsP9MzaKNhwqY8IdWCHDthuC7jVdI2Yiww2zAMp6nFV1Cv2kh/Oji9LSjJGv2dJ0iIP3eekXpZE3bpwDMoGdQsSH4Z2sVdpQJRfaTea326meyZXPvjMPWIA90bFIoP1UERXrAvh5RfXB3J1VTwNyfbz91CvtQxqbABf6RBQy32wVHblw5IpGjAqgztnjsCS7J4qoYywmgWNvtMrGZvKj1UPyArcuZGw3UkJW6+wPldyrHR5hyvaW/bzjiAGTke/3xzgt2vO93zs3Ui9ThiLvVA1On3MHmepB4cj8/+9FboswSTIhjJAblNrdK+z90AuYdkvvauoSQrgA1ViTZiKGS+GPTWsN83S6wJvXObUHoJX969HBxrm7R+yXUP2736tX63GDjEhUr1z+o3ZdLcYkwRj9F1lAsLt2Zt978Tfn6TEAdCsQU92DB5YDwI9jQzm6yNB4lOQoMZoofRI9hD0r4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
